//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.01 at 01:08:39 PM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://shdwrazedev.com/metro_upd", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.shdwrazedev.metro_upd;
