
package com.sever0x.server.service;

import java.util.List;

import com.sever0x.server.service.metro_upd.Return;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "StationService", targetNamespace = "http://service.server.sever0x.com/")
@XmlSeeAlso({
    com.sever0x.server.service.metro_upd.ObjectFactory.class,
    com.sever0x.server.service.ObjectFactory.class
})
public interface StationService {


    /**
     * 
     * @param id
     * @return
     *     returns com.sever0x.server.service.metro_upd.Return
     * @throws DAOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.server.sever0x.com/metro_upd")
    @RequestWrapper(localName = "getStation", targetNamespace = "http://service.server.sever0x.com/", className = "com.sever0x.server.service.GetStation")
    @ResponseWrapper(localName = "getStationResponse", targetNamespace = "http://service.server.sever0x.com/", className = "com.sever0x.server.service.GetStationResponse")
    @Action(input = "http://service.server.sever0x.com/StationService/getStationRequest", output = "http://service.server.sever0x.com/StationService/getStationResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://service.server.sever0x.com/StationService/getStation/Fault/DAOException")
    })
    public com.sever0x.server.service.metro_upd.Return getStation(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws DAOException_Exception
    ;

    /**
     * 
     * @param clientToken
     * @param parameters
     * @param serverToken
     * @return
     *     returns com.sever0x.server.service.DeleteStationResponse
     * @throws DAOException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteStationResponse", targetNamespace = "http://service.server.sever0x.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://service.server.sever0x.com/StationService/deleteStationRequest", output = "http://service.server.sever0x.com/StationService/deleteStationResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://service.server.sever0x.com/StationService/deleteStation/Fault/DAOException")
    })
    public DeleteStationResponse deleteStation(
        @WebParam(name = "deleteStation", targetNamespace = "http://service.server.sever0x.com/", partName = "parameters")
        DeleteStation parameters,
        @WebParam(name = "clientToken", targetNamespace = "http://service.server.sever0x.com/", header = true, partName = "clientToken")
        String clientToken,
        @WebParam(name = "serverToken", targetNamespace = "http://service.server.sever0x.com/", header = true, mode = WebParam.Mode.OUT, partName = "serverToken")
        Holder<String> serverToken)
        throws DAOException_Exception
    ;

    /**
     * 
     * @param line
     * @return
     *     returns java.util.List<com.sever0x.server.service.metro_upd.Return>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.server.sever0x.com/metro_upd")
    @RequestWrapper(localName = "getStationsByLine", targetNamespace = "http://service.server.sever0x.com/", className = "com.sever0x.server.service.GetStationsByLine")
    @ResponseWrapper(localName = "getStationsByLineResponse", targetNamespace = "http://service.server.sever0x.com/", className = "com.sever0x.server.service.GetStationsByLineResponse")
    @Action(input = "http://service.server.sever0x.com/StationService/getStationsByLineRequest", output = "http://service.server.sever0x.com/StationService/getStationsByLineResponse")
    public List<com.sever0x.server.service.metro_upd.Return> getStationsByLine(
        @WebParam(name = "line", targetNamespace = "")
        String line);

    /**
     * 
     * @param station
     * @return
     *     returns com.sever0x.server.service.AddStationResponse.Return
     * @throws DAOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addStation", targetNamespace = "http://service.server.sever0x.com/", className = "com.sever0x.server.service.AddStation")
    @ResponseWrapper(localName = "addStationResponse", targetNamespace = "http://service.server.sever0x.com/", className = "com.sever0x.server.service.AddStationResponse")
    @Action(input = "http://service.server.sever0x.com/StationService/addStationRequest", output = "http://service.server.sever0x.com/StationService/addStationResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://service.server.sever0x.com/StationService/addStation/Fault/DAOException")
    })
    public com.sever0x.server.service.AddStationResponse.Return addStation(
        @WebParam(name = "station", targetNamespace = "http://service.server.sever0x.com/metro_upd")
        Return station)
        throws DAOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.sever0x.server.service.metro_upd.Return>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.server.sever0x.com/metro_upd")
    @RequestWrapper(localName = "getAllStations", targetNamespace = "http://service.server.sever0x.com/", className = "com.sever0x.server.service.GetAllStations")
    @ResponseWrapper(localName = "getAllStationsResponse", targetNamespace = "http://service.server.sever0x.com/", className = "com.sever0x.server.service.GetAllStationsResponse")
    @Action(input = "http://service.server.sever0x.com/StationService/getAllStationsRequest", output = "http://service.server.sever0x.com/StationService/getAllStationsResponse")
    public List<com.sever0x.server.service.metro_upd.Return> getAllStations();

    /**
     * 
     * @param city
     * @return
     *     returns java.util.List<com.sever0x.server.service.metro_upd.Return>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.server.sever0x.com/metro_upd")
    @RequestWrapper(localName = "getStationsByCity", targetNamespace = "http://service.server.sever0x.com/", className = "com.sever0x.server.service.GetStationsByCity")
    @ResponseWrapper(localName = "getStationsByCityResponse", targetNamespace = "http://service.server.sever0x.com/", className = "com.sever0x.server.service.GetStationsByCityResponse")
    @Action(input = "http://service.server.sever0x.com/StationService/getStationsByCityRequest", output = "http://service.server.sever0x.com/StationService/getStationsByCityResponse")
    public List<com.sever0x.server.service.metro_upd.Return> getStationsByCity(
        @WebParam(name = "city", targetNamespace = "")
        String city);

}
