//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.01 at 01:08:39 PM EET 
//


package com.sever0x.model.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for line.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="line"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Холодногірсько-заводська лінія"/&gt;
 *     &lt;enumeration value="Олексіївська лінія"/&gt;
 *     &lt;enumeration value="Салтівська лінія"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "line")
@XmlEnum
public enum Line {

    @XmlEnumValue("\u0425\u043e\u043b\u043e\u0434\u043d\u043e\u0433\u0456\u0440\u0441\u044c\u043a\u043e-\u0437\u0430\u0432\u043e\u0434\u0441\u044c\u043a\u0430 \u043b\u0456\u043d\u0456\u044f")
    ХОЛОДНОГІРСЬКО_ЗАВОДСЬКА_ЛІНІЯ("\u0425\u043e\u043b\u043e\u0434\u043d\u043e\u0433\u0456\u0440\u0441\u044c\u043a\u043e-\u0437\u0430\u0432\u043e\u0434\u0441\u044c\u043a\u0430 \u043b\u0456\u043d\u0456\u044f"),
    @XmlEnumValue("\u041e\u043b\u0435\u043a\u0441\u0456\u0457\u0432\u0441\u044c\u043a\u0430 \u043b\u0456\u043d\u0456\u044f")
    ОЛЕКСІЇВСЬКА_ЛІНІЯ("\u041e\u043b\u0435\u043a\u0441\u0456\u0457\u0432\u0441\u044c\u043a\u0430 \u043b\u0456\u043d\u0456\u044f"),
    @XmlEnumValue("\u0421\u0430\u043b\u0442\u0456\u0432\u0441\u044c\u043a\u0430 \u043b\u0456\u043d\u0456\u044f")
    САЛТІВСЬКА_ЛІНІЯ("\u0421\u0430\u043b\u0442\u0456\u0432\u0441\u044c\u043a\u0430 \u043b\u0456\u043d\u0456\u044f");
    private final String value;

    Line(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Line fromValue(String v) {
        for (Line c: Line.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
